name: Build and Deploy Docs

on:
  # Deploy on push to main
  push:
    branches: [main]
  # Deploy on pull requests in main repo
  pull_request:
    branches: [main]
  # Deploy on workflow dispatch
  workflow_dispatch: {}

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    # Only run on main repo, not forks
    if: github.repository == 'marimo-team/marimo'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: ⚡ Install Vercel CLI
        run: npm install --global vercel@latest

      - name: ⬇️ Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: 📚 Build docs
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: 📚 llms.txt
        # This is technically off by 1 commit, but generating the llms.txt file is easiest from a
        # deployed site.
        # We also ignore txt and xml files
        run: npx sitefetch https://docs.marimo.io -o ${{ env.OUTPUT_FILE }} --match '!**/*.{txt,xml}'
        env:
          OUTPUT_FILE: .vercel/output/static/llms.txt

      - name: 🚀 Deploy to Vercel
        # Deploy to production for main branch, preview for PRs
        run: |
          if [ ${{ github.ref == 'refs/heads/main' }} = true ]; then
            vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          fi
